version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache-latest
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
    - "8000:80"

  composer:
    image: composer
    ports:
      - "8001:80"
    volumes:
      - ./composer.json:/composer/composer.json
      - ./vendor:/composer/vendor
    container_name: composer
    working_dir: /composer
    command: install
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    ports:
      - "3306:3306"